apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gradeapp-hpa
  namespace: gradeapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gradeapp-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Target CPU usage is 50%
