apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-pod
spec:
  containers:
    - name: busybox
      image: ubuntu:latest
      command:
        - sleep
        - "3600"  # Keep the pod running for 1 hour
