apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-example-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: pvc-container
        image: nginx:latest
        volumeMounts:
        - name: my-pvc-volume
          mountPath: /usr/share/nginx/html  # Mount path inside the container
      volumes:
      - name: my-pvc-volume
        persistentVolumeClaim:
          claimName: my-pvc  # Use the PVC
