apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
data:
  accesskey: QUtJQVEzRUdVU1hXSkVVTUZXWE8=
  secretkey: RzhZK3RHRkttTjM2MnN3anFheXVsTWQ2bXRRa1JRVitGNGtOeDlDNg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-deployment
spec: # Corrected indentation
  replicas: 3
  selector:
    matchLabels:
      app: aws-app
  template:
    metadata:
      labels:
        app: aws-app
    spec:
      containers:
        - name: aws-container
          image: nginx:latest
          imagePullPolicy: Always
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secretkey
            - name: AWS_REGION
              value: us-east-1
