apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Release.Name }}--{{ .Chart.Name }}
 labels:
    app: nginx
  annotations:
     app.kubernetes.io/managed-by: {{ .Release.Service }}
    # Quote Function
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}        
    # Pipeline
    app.kubernetes.io/managed-by: {{ .Release.Service | quote | upper | lower }}        
    # default Function
    app.kubernetes.io/name: {{ default "sample" .Values.releaseName | lower }}
    # Controlling Leading and Trailing White spaces 
    leading-whitespace: "   {{- .Chart.Name }}    Ops"
    trailing-whitespace: "   {{ .Chart.Name -}}    Ops"
    leadtrail-whitespace: "   {{- .Chart.Name -}}    Ops"   
    # indent function
    indenttest: "  {{- .Chart.Name | indent 4 -}}  "  
    # nindent function
    nindenttest: "  {{- .Chart.Name | nindent 4 -}}  " 